name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'  # Dispara quando uma nova tag de versão é criada

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push front-end image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

      - name: Push back-end image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-image:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest

      - name: Push database image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/database-image:latest ./database
          docker push ${{ secrets.DOCKER_USERNAME }}/database-image:latest

